# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2
env_variables:
  PUSHER_APP_ID: "1789620"
  PUSHER_KEY: "87dd3817ca48322d3e02"
  PUSHER_SECRET: "995b9aea5d280fbadffa"
  PUSHER_CLUSTER: "eu"

resources:
  cpu: 4
  memory_gb: 2
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5

