# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2
env_variables:
  PUSHER_APP_ID: "1790013"
  PUSHER_KEY: "19cbfeaeb11cb7adbda4"
  PUSHER_SECRET: "25d9fa7228b4648f110a"
  PUSHER_CLUSTER: "eu"
  UNSPLASH_API_accessKey: "PWHJuYQL8bteX-4JFPeu_Io6DfznbwLiA9ze5tWRTlI"
  UNSPLASH_API_secretKey: "zZ602hyHh-uc_4uKq4CS7IoYWfZz7itzl14In2ttD9Y"