# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2
env_variables:
  UNSPLASH_API_accessKey: "PWHJuYQL8bteX-4JFPeu_Io6DfznbwLiA9ze5tWRTlI"
  UNSPLASH_API_secretKey: "zZ602hyHh-uc_4uKq4CS7IoYWfZz7itzl14In2ttD9Y"
  PUSHER_APP_ID: "1789620"
  PUSHER_KEY: "87dd3817ca48322d3e02"
  PUSHER_SECRET: "995b9aea5d280fbadffa"
  PUSHER_CLUSTER: "eu"

resources:
  cpu: 8
  memory_gb: 4
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5

automatic_scaling:
  min_instances: 1
